# Tensor数据类型

## 导入库

In [1]:
import tensorflow as tf
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import sklearn
import pandas as pd
import os
import sys
import time
from tensorflow import keras

print(sys.version_info)
for module in mpl, np, pd, sklearn, tf, keras:
    print(module.__name__ + "的版本为：" + module.__version__)

sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)
matplotlib的版本为：3.1.1
numpy的版本为：1.16.5
pandas的版本为：0.25.3
sklearn的版本为：0.21.3
tensorflow的版本为：2.0.0
tensorflow_core.keras的版本为：2.2.4-tf


## tf.constant()

In [2]:
tf.constant(1) # 常量1，其数据可以更改

<tf.Tensor: id=0, shape=(), dtype=int32, numpy=1>

In [3]:
tf.constant(1.) # 常量1.0，其数据可以更改，为float型

<tf.Tensor: id=1, shape=(), dtype=float32, numpy=1.0>

In [4]:
tf.constant(2.2, dtype=tf.int32) # 强制将f1oat型设置为int型，会报错

TypeError: Cannot convert 2.2 to EagerTensor of dtype int32

In [5]:
tf.constant(2., dtype=tf.double) # 将float可以强制设置为double型

<tf.Tensor: id=3, shape=(), dtype=float64, numpy=2.0>

In [6]:
tf.constant([True, False]) # bool型变量

<tf.Tensor: id=4, shape=(2,), dtype=bool, numpy=array([ True, False])>

In [7]:
tf.constant('Hello World!') # string类型变量

<tf.Tensor: id=5, shape=(), dtype=string, numpy=b'Hello World!'>

In [11]:
tf.constant(np.array(2.0))

<tf.Tensor: id=21, shape=(), dtype=float64, numpy=2.0>

In [12]:
tf.constant(np.array(2.0), dtype=tf.float32)

<tf.Tensor: id=22, shape=(), dtype=float32, numpy=2.0>

In [8]:
tf.constant([[1, 2], [3, 4], [5, 6]])

<tf.Tensor: id=6, shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [10]:
with tf.device("cpu"):
    a = tf.constant([1])
with tf.device("gpu"):
    a = tf.range(4)
    
a.device
b.device

NameError: name 'b' is not defined

## tensorflow中的shape

In [10]:
np.shape(0)

()

In [11]:
np.shape([0])

(1,)

In [12]:
np.shape([1, 2, 3])

(3,)

In [13]:
np.shape([[1], [2]])

(2, 1)

In [14]:
a = np.zeros([2, 3])
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.shape(a)

(2, 3)

In [16]:
np.shape(a)[1]

3

In [17]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [18]:
b.shape

(3, 3)

In [19]:
b.shape[0]

3

In [20]:
c = [1, 2, 3]

In [21]:
c.shape

AttributeError: 'list' object has no attribute 'shape'

## isinstance(a,tf.Tensor) || tf.is_tensor(b) || a.dtype

In [22]:
a = tf.constant([1.])
b = tf.constant([True, False])
c = tf.constant('hello,world.')
d = np.arange(4)

In [23]:
isinstance(a, tf.Tensor)

True

In [24]:
tf.is_tensor(b)

True

In [25]:
tf.is_tensor(d)

False

In [26]:
a.dtype, b.dtype, c.dtype

(tf.float32, tf.bool, tf.string)

In [27]:
a.dtype == tf.float32

True

In [28]:
c.dtype == tf.string

True

## tf.convert_to_tensor() || tf.cast()

In [29]:
a = np.arange(5)     # a为numpy类型的数组，其dtype为int32
a

array([0, 1, 2, 3, 4])

In [30]:
a.dtype

dtype('int32')

In [31]:
aa = tf.convert_to_tensor(a)     # 将numpy转换为tensor，其dtype与a默认一致
aa

<tf.Tensor: id=15, shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4])>

In [32]:
aa = tf.convert_to_tensor(a, dtype=tf.int16)     # 指定数据类型为int16
aa

<tf.Tensor: id=16, shape=(5,), dtype=int16, numpy=array([0, 1, 2, 3, 4], dtype=int16)>

In [33]:
tf.cast(aa, dtype=tf.float32)      # 张量数据类型转换为float32

<tf.Tensor: id=17, shape=(5,), dtype=float32, numpy=array([0., 1., 2., 3., 4.], dtype=float32)>

In [34]:
aaa = tf.cast(aa, dtype=tf.double)     # 张量数据类型转换为double
aaa

<tf.Tensor: id=18, shape=(5,), dtype=float64, numpy=array([0., 1., 2., 3., 4.])>

In [35]:
tf.cast(aaa, dtype=tf.int32)     # 张量数据类型转换为int32

<tf.Tensor: id=19, shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4])>

In [36]:
b = tf.constant([0, 1])     # int32类型的tensor
b

<tf.Tensor: id=20, shape=(2,), dtype=int32, numpy=array([0, 1])>

In [37]:
bb = tf.cast(b, dtype=tf.bool)     # 转换为bool类型
bb

<tf.Tensor: id=21, shape=(2,), dtype=bool, numpy=array([False,  True])>

In [38]:
tf.cast(bb, dtype=tf.int32)     # 转换回int32类型

<tf.Tensor: id=22, shape=(2,), dtype=int32, numpy=array([0, 1])>

## tf.Variable()

In [39]:
tf.Variable(1.0)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>

In [40]:
isinstance(tf.Variable(1.0), tf.Tensor)

False

In [41]:
type(tf.Variable(1.0))

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [42]:
    tf.is_tensor(tf.Variable(1.0))

True

In [43]:
a = tf.Variable(1.0)
a.assign(2.0)     # 改变tensor的值
a

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.0>

In [44]:
a.trainable

True

In [45]:
b = tf.constant(1.0)
try:
    print(b.trainable)
    b.assign(2.0)
except Exception as e:
    print('error', e)

error 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'trainable'


In [46]:
a = tf.range(5)
a

<tf.Tensor: id=66, shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4])>

In [47]:
b = tf.Variable(a)      # 对tensor类型a再进行Variable属性的包装
b.dtype

tf.int32

In [48]:
b.name

'Variable:0'

In [49]:
b = tf.Variable(a, name='input_data')
b.name

'input_data:0'

In [50]:
b.trainable

True

In [51]:
isinstance(b, tf.Tensor)

False

In [52]:
tf.is_tensor(b)

True

## To numpy

In [53]:
b.numpy()     # Variable转换为numpy

array([0, 1, 2, 3, 4])

In [54]:
a.numpy()

array([0, 1, 2, 3, 4])

In [55]:
b.numpy()

array([0, 1, 2, 3, 4])

In [56]:
a = tf.ones([])
a.numpy()

1.0

In [57]:
int(a)

1

In [58]:
float(a)

1.0

# 创建Tensor

## From Numpy, List

In [59]:
tf.convert_to_tensor(np.ones([2, 3]))

<tf.Tensor: id=82, shape=(2, 3), dtype=float64, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]])>

In [60]:
tf.convert_to_tensor(np.zeros([2, 3]))

<tf.Tensor: id=83, shape=(2, 3), dtype=float64, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]])>

In [61]:
tf.convert_to_tensor([1, 2])

<tf.Tensor: id=84, shape=(2,), dtype=int32, numpy=array([1, 2])>

In [62]:
tf.convert_to_tensor([1, 2.])

<tf.Tensor: id=85, shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [63]:
tf.convert_to_tensor([[1], [2.]])

<tf.Tensor: id=86, shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [2.]], dtype=float32)>

## tf.zeros()

In [64]:
tf.zeros([])

<tf.Tensor: id=87, shape=(), dtype=float32, numpy=0.0>

In [65]:
tf.zeros([1])

<tf.Tensor: id=90, shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>

In [66]:
tf.zeros([2, 2])

<tf.Tensor: id=93, shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [67]:
tf.zeros([2, 3, 3])

<tf.Tensor: id=96, shape=(2, 3, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

## tf.zeros_like()

In [68]:
a = tf.zeros([2, 3, 3])

tf.zeros_like(a)

<tf.Tensor: id=100, shape=(2, 3, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [70]:
tf.zeros(a.shape)

<tf.Tensor: id=105, shape=(2, 3, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

## tf.ones()

In [71]:
tf.ones(1)

<tf.Tensor: id=108, shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

In [72]:
tf.ones([])

<tf.Tensor: id=109, shape=(), dtype=float32, numpy=1.0>

In [76]:
tf.ones([2])

<tf.Tensor: id=121, shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>

In [74]:
tf.ones([2, 3])

<tf.Tensor: id=115, shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [77]:
tf.ones_like(a)

<tf.Tensor: id=124, shape=(2, 3, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

## fill

In [78]:
tf.fill([2, 2], 0)

<tf.Tensor: id=127, shape=(2, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0]])>

In [79]:
tf.fill([2, 2], 0.)

<tf.Tensor: id=130, shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [80]:
tf.fill([2, 2], 1)

<tf.Tensor: id=133, shape=(2, 2), dtype=int32, numpy=
array([[1, 1],
       [1, 1]])>

In [81]:
tf.fill([2, 2], 9)

<tf.Tensor: id=136, shape=(2, 2), dtype=int32, numpy=
array([[9, 9],
       [9, 9]])>

## normal

In [83]:
tf.random.normal([2, 2], mean=1, stddev=1)

<tf.Tensor: id=148, shape=(2, 2), dtype=float32, numpy=
array([[ 2.3736386 ,  2.2542825 ],
       [ 0.9523016 , -0.36386502]], dtype=float32)>

In [84]:
tf.random.normal([2, 2])

<tf.Tensor: id=154, shape=(2, 2), dtype=float32, numpy=
array([[0.7626046 , 0.02452154],
       [0.02709651, 2.0158293 ]], dtype=float32)>

In [85]:
tf.random.truncated_normal([2, 2], mean=0, stddev=1)

<tf.Tensor: id=160, shape=(2, 2), dtype=float32, numpy=
array([[ 0.8914037 , -0.17170063],
       [-0.4411633 , -0.1195259 ]], dtype=float32)>

## uniform

In [86]:
tf.random.uniform([2, 2], minval=0, maxval=1)

<tf.Tensor: id=167, shape=(2, 2), dtype=float32, numpy=
array([[0.147107 , 0.0786376],
       [0.830403 , 0.5752758]], dtype=float32)>

In [87]:
tf.random.uniform([2, 2], minval=0, maxval=100)

<tf.Tensor: id=174, shape=(2, 2), dtype=float32, numpy=
array([[ 5.421591, 76.12483 ],
       [36.80719 , 83.26929 ]], dtype=float32)>

## Random Permutation

In [92]:
idx = tf.range(10)
idx = tf.random.shuffle(idx)

idx

<tf.Tensor: id=204, shape=(10,), dtype=int32, numpy=array([4, 7, 2, 8, 6, 3, 1, 9, 5, 0])>

In [94]:
a = tf.random.normal([10, 784])
b = tf.random.uniform([10], maxval=10, dtype=tf.int32)

<tf.Tensor: id=224, shape=(10,), dtype=int32, numpy=array([0, 4, 9, 5, 6, 1, 0, 3, 2, 5])>

In [95]:
a

<tf.Tensor: id=220, shape=(10, 784), dtype=float32, numpy=
array([[-0.02290396,  0.56215954,  0.10735991, ...,  1.2167947 ,
        -0.38496277,  0.12042931],
       [ 1.0742613 , -0.34319082, -0.80830973, ..., -1.4117931 ,
        -0.06094613,  1.2927175 ],
       [ 1.3226695 ,  0.50710416,  0.72811073, ...,  2.369059  ,
        -0.5621931 , -0.91920185],
       ...,
       [ 0.64534193, -0.5943472 ,  0.27152726, ..., -1.3712796 ,
         1.5476067 ,  0.36032626],
       [-0.9423677 , -0.5703136 , -0.17020604, ..., -1.2840626 ,
        -1.867614  ,  0.49486792],
       [ 1.4849142 ,  0.88193196, -0.12123332, ..., -1.6731986 ,
        -0.03913584, -0.9320491 ]], dtype=float32)>

In [96]:
b

<tf.Tensor: id=224, shape=(10,), dtype=int32, numpy=array([0, 4, 9, 5, 6, 1, 0, 3, 2, 5])>

In [98]:
a = tf.gather(a, idx)
a

<tf.Tensor: id=228, shape=(10, 784), dtype=float32, numpy=
array([[-1.3121902 , -0.17115591,  1.1612656 , ..., -0.22030963,
        -1.0287231 ,  1.2493622 ],
       [ 1.4849142 ,  0.88193196, -0.12123332, ..., -1.6731986 ,
        -0.03913584, -0.9320491 ],
       [ 1.3226695 ,  0.50710416,  0.72811073, ...,  2.369059  ,
        -0.5621931 , -0.91920185],
       ...,
       [-0.02290396,  0.56215954,  0.10735991, ...,  1.2167947 ,
        -0.38496277,  0.12042931],
       [-0.79148334, -0.640083  ,  0.5134212 , ..., -0.3238861 ,
         3.1900673 , -1.0401059 ],
       [ 0.67446166,  0.10826838, -0.41634735, ..., -0.1266362 ,
         0.1756315 ,  2.2268245 ]], dtype=float32)>

In [99]:
b = tf.gather(b, idx)
b

<tf.Tensor: id=230, shape=(10,), dtype=int32, numpy=array([6, 3, 9, 2, 0, 5, 4, 5, 1, 0])>

## tf.constant

In [100]:
tf.constant(1)

<tf.Tensor: id=231, shape=(), dtype=int32, numpy=1>

In [101]:
tf.constant([1])

<tf.Tensor: id=232, shape=(1,), dtype=int32, numpy=array([1])>

In [102]:
tf.constant([1, 2.])

<tf.Tensor: id=233, shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [103]:
tf.constant([[1, 2.], [3.]])

ValueError: Can't convert non-rectangular Python sequence to Tensor.

## Loss

In [105]:
out = tf.random.uniform([4, 10])
out

<tf.Tensor: id=248, shape=(4, 10), dtype=float32, numpy=
array([[0.2974161 , 0.85970914, 0.9867983 , 0.42287338, 0.2411375 ,
        0.2865194 , 0.53751266, 0.705619  , 0.07453382, 0.9987173 ],
       [0.448779  , 0.75331664, 0.8077569 , 0.84403324, 0.14616907,
        0.12823665, 0.7249241 , 0.25756466, 0.37843072, 0.53962946],
       [0.7101717 , 0.8032317 , 0.5579879 , 0.648047  , 0.27858996,
        0.55792725, 0.59039295, 0.19450045, 0.3274747 , 0.49129796],
       [0.53328776, 0.9635261 , 0.8141471 , 0.58182037, 0.7314079 ,
        0.29829335, 0.01914048, 0.24545288, 0.03839147, 0.13164544]],
      dtype=float32)>

In [106]:
y = tf.range(4)
y = tf.one_hot(y, depth=10)
y

<tf.Tensor: id=256, shape=(4, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [108]:
loss = tf.keras.losses.mse(y, out)
loss

<tf.Tensor: id=262, shape=(4,), dtype=float32, numpy=array([0.43153667, 0.2691193 , 0.28887674, 0.27538425], dtype=float32)>

In [109]:
loss = tf.reduce_mean(loss)
loss

<tf.Tensor: id=264, shape=(), dtype=float32, numpy=0.31622922>

## Vector

In [111]:
net = tf.keras.layers.Dense(10)
net.build((4, 8))
net.kernel

<tf.Variable 'kernel:0' shape=(8, 10) dtype=float32, numpy=
array([[-0.52973306, -0.44426042, -0.49167407,  0.04949629, -0.15328255,
        -0.20396894,  0.09675366, -0.11199743,  0.03434932, -0.06655443],
       [ 0.50150895,  0.14248562,  0.17708474, -0.5316042 ,  0.40628773,
         0.32327604,  0.35689843,  0.5168618 ,  0.00086951, -0.18623331],
       [-0.16826475, -0.48936194,  0.0886817 ,  0.52782667, -0.17349824,
        -0.21789566,  0.37256944,  0.3244136 ,  0.26242703, -0.2865637 ],
       [ 0.38313633, -0.49228758,  0.1442678 , -0.35119498,  0.26517493,
         0.30674392,  0.49025953, -0.22259107, -0.0934031 , -0.51542246],
       [ 0.10421395, -0.12105885, -0.26194632,  0.2655847 , -0.5595506 ,
        -0.4284563 ,  0.49833882,  0.00077635, -0.53981036,  0.05787784],
       [-0.02881807, -0.3261707 ,  0.36831796, -0.32212543,  0.49305606,
         0.5640254 , -0.18394542,  0.13749546,  0.2620325 ,  0.18681431],
       [-0.5653845 , -0.14890552, -0.19004595, -0.4456123 

In [112]:
net.bias

<tf.Variable 'bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

## Matrix

In [114]:
x = tf.random.normal([4, 784])

In [115]:
net = tf.keras.layers.Dense(10)

In [116]:
net.build((4, 784))

In [117]:
net(x).shape

TensorShape([4, 10])

In [118]:
net.kernel.shape

TensorShape([784, 10])

In [119]:
net.bias.shape

TensorShape([10])

## Dim

In [120]:
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.imdb.load_data(num_words=10000)

In [121]:
x_train = keras.preprocessing.sequence.pad_sequences(x_train, maxlen=80)
x_train.shape

(25000, 80)

In [125]:
emb = keras.layers.Embedding(x_train)

TypeError: __init__() missing 1 required positional argument: 'output_dim'

# 索引与切片

## Basic indexing

In [126]:
a = tf.ones([1, 5, 5, 3])
a[0][0]

<tf.Tensor: id=337, shape=(5, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [127]:
a[0][0][0]

<tf.Tensor: id=349, shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>

In [132]:
a[0][0][0][2]

<tf.Tensor: id=373, shape=(), dtype=float32, numpy=1.0>

## Numpy-style indexing

In [133]:
a = tf.random.normal([4, 28, 28, 3])

In [134]:
a[1].shape

TensorShape([28, 28, 3])

In [135]:
a[1, 2].shape

TensorShape([28, 3])

In [137]:
a[1, 2, 3].shape

TensorShape([3])

In [138]:
a[1, 2, 3, 2].shape

TensorShape([])

## Indexing by : start:end

In [139]:
a = tf.range(10)

In [140]:
a[-1:]

<tf.Tensor: id=411, shape=(1,), dtype=int32, numpy=array([9])>

In [141]:
a[-2:]

<tf.Tensor: id=415, shape=(2,), dtype=int32, numpy=array([8, 9])>

In [142]:
a[:2]

<tf.Tensor: id=419, shape=(2,), dtype=int32, numpy=array([0, 1])>

In [143]:
a[:-1]

<tf.Tensor: id=423, shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8])>

In [145]:
a = tf.random.normal([4, 28, 28, 3])
a.shape

TensorShape([4, 28, 28, 3])

In [146]:
a[0].shape

TensorShape([28, 28, 3])

In [147]:
a[0,:,:,:].shape

TensorShape([28, 28, 3])

In [148]:
a[0,1,:,:].shape

TensorShape([28, 3])

In [149]:
a[:,:,:,0].shape

TensorShape([4, 28, 28])

In [150]:
a[:,0,:,:].shape

TensorShape([4, 28, 3])

## Indexing by : start:end:step

In [151]:
a[0:2,:,:,:].shape

TensorShape([2, 28, 28, 3])

In [152]:
a[:,0:28:2,0:28:2,:].shape

TensorShape([4, 14, 14, 3])

In [153]:
a[:,14:,14:,:].shape

TensorShape([4, 14, 14, 3])

In [154]:
a[:,::2,::2,:].shape

TensorShape([4, 14, 14, 3])

In [155]:
a = tf.range(4)
a[::-1]

<tf.Tensor: id=473, shape=(4,), dtype=int32, numpy=array([3, 2, 1, 0])>

In [156]:
a[::-2]

<tf.Tensor: id=477, shape=(2,), dtype=int32, numpy=array([3, 1])>

In [163]:
a[2::-2]

<tf.Tensor: id=505, shape=(2,), dtype=int32, numpy=array([2, 0])>

## tf.gather()

In [168]:
a = tf.ones([4, 35, 8])

In [169]:
tf.gather(a, axis=0, indices=[2, 3]).shape

TensorShape([2, 35, 8])

In [170]:
a[2:4].shape

TensorShape([2, 35, 8])

In [173]:
tf.gather(a, axis=0, indices=[2, 1, 3, 0]).shape

TensorShape([4, 35, 8])

In [175]:
tf.gather(a, axis=1, indices=[2, 3, 7, 9, 16]).shape

TensorShape([4, 5, 8])

In [176]:
tf.gather(a, axis=2, indices=[2, 3, 7]).shape

TensorShape([4, 35, 3])

## tf.gather_nd()

In [177]:
tf.gather_nd(a, [0]).shape

TensorShape([35, 8])

In [178]:
tf.gather_nd(a, [0, 1]).shape

TensorShape([8])

In [179]:
tf.gather_nd(a, [0, 1, 2]).shape

TensorShape([])

In [180]:
tf.gather_nd(a, [[0, 1, 2]]).shape

TensorShape([1])

In [181]:
tf.gather_nd(a, [[0, 0], [1, 1]]).shape

TensorShape([2, 8])

In [182]:
tf.gather_nd(a, [[0, 0], [1, 1], [2, 2]]).shape

TensorShape([3, 8])

In [183]:
tf.gather_nd(a, [[0, 0, 0], [1, 1, 1], [2, 2, 2]]).shape

TensorShape([3])

In [184]:
tf.gather_nd(a, [[[0, 0, 0], [1, 1, 1], [2, 2, 2]]]).shape

TensorShape([1, 3])

## tf.boolean_mask

In [185]:
a = tf.ones([4, 28, 28, 3])
a.shape

TensorShape([4, 28, 28, 3])

In [186]:
tf.boolean_mask(a, mask=[True, True, False, False]).shape

TensorShape([2, 28, 28, 3])

In [187]:
tf.boolean_mask(a, mask=[True, True, False], axis=3).shape

TensorShape([4, 28, 28, 2])

In [191]:
a = tf.ones([2, 3, 4])

In [200]:
tf.boolean_mask(a, mask=[[True, False, False], [False, True, True]])

<tf.Tensor: id=913, shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

# 维度变换

## tf.reshape()

In [202]:
a = tf.random.normal([4, 28, 28, 3])
print(a.shape)
print(a.ndim)

(4, 28, 28, 3)
4


In [203]:
tf.reshape(a, [4, 28*28, 3]).shape

TensorShape([4, 784, 3])

In [204]:
tf.reshape(a, [4, -1, 3]).shape

TensorShape([4, 784, 3])

In [207]:
tf.reshape(a, [4, 784*3]).shape

TensorShape([4, 2352])

In [208]:
tf.reshape(a, [4, -1]).shape

TensorShape([4, 2352])

In [209]:
tf.reshape(tf.reshape(a, [4, -1]),[4, 28, 28, 3]).shape

TensorShape([4, 28, 28, 3])

In [210]:
tf.reshape(tf.reshape(a, [4, -1]),[4, -1, 3]).shape

TensorShape([4, 784, 3])

## tf.transpose()

In [211]:
a = tf.random.normal([4, 3, 2, 1])
a.shape

TensorShape([4, 3, 2, 1])

In [212]:
tf.transpose(a).shape

TensorShape([1, 2, 3, 4])

In [213]:
a = tf.random.normal([4, 28, 28, 3])
a.shape

TensorShape([4, 28, 28, 3])

In [214]:
tf.transpose(a, perm=[0,3,1,2]).shape

TensorShape([4, 3, 28, 28])

## tf.expand_dim()

In [215]:
a = tf.ones([4, 35, 10])
a.shape

TensorShape([4, 35, 10])

In [216]:
tf.expand_dims(a, axis=0).shape

TensorShape([1, 4, 35, 10])

In [217]:
tf.expand_dims(a, axis=-1).shape

TensorShape([4, 35, 10, 1])

In [218]:
tf.expand_dims(a, axis=-2).shape

TensorShape([4, 35, 1, 10])

## tf.squeeze()

In [219]:
a = tf.ones([1, 4, 1, 35, 1, 10])
tf.squeeze(a).shape

TensorShape([4, 35, 10])

In [220]:
a = tf.zeros([1, 2, 1, 3])
a.shape

TensorShape([1, 2, 1, 3])

In [221]:
tf.squeeze(a, axis=0).shape

TensorShape([2, 1, 3])

In [222]:
tf.squeeze(a, axis=2).shape

TensorShape([1, 2, 3])

In [223]:
tf.squeeze(a, axis=-2).shape

TensorShape([1, 2, 3])

In [224]:
tf.squeeze(a, axis=-4).shape

TensorShape([2, 1, 3])

In [225]:
tf.squeeze(a).shape

TensorShape([2, 3])

# Tensor数学运算

## 导入库

In [1]:
import tensorflow as tf
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import sklearn
import pandas as pd
import os
import sys
import time
from tensorflow import keras

print(sys.version_info)
for module in mpl, np, pd, sklearn, tf, keras:
    print(module.__name__ + "的版本为：" + module.__version__)

sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
matplotlib的版本为：3.0.3
numpy的版本为：1.16.2
pandas的版本为：0.24.2
sklearn的版本为：0.20.3
tensorflow的版本为：2.0.0
tensorflow_core.keras的版本为：2.2.4-tf


## + - * / % //

In [2]:
a = tf.ones([2, 2])
b = tf.fill([2, 2], 2.)

In [3]:
a + b, a - b, a * b, a / b

(<tf.Tensor: id=6, shape=(2, 2), dtype=float32, numpy=
 array([[3., 3.],
        [3., 3.]], dtype=float32)>,
 <tf.Tensor: id=7, shape=(2, 2), dtype=float32, numpy=
 array([[-1., -1.],
        [-1., -1.]], dtype=float32)>,
 <tf.Tensor: id=8, shape=(2, 2), dtype=float32, numpy=
 array([[2., 2.],
        [2., 2.]], dtype=float32)>,
 <tf.Tensor: id=9, shape=(2, 2), dtype=float32, numpy=
 array([[0.5, 0.5],
        [0.5, 0.5]], dtype=float32)>)

In [4]:
b // a, b % a

(<tf.Tensor: id=10, shape=(2, 2), dtype=float32, numpy=
 array([[2., 2.],
        [2., 2.]], dtype=float32)>,
 <tf.Tensor: id=11, shape=(2, 2), dtype=float32, numpy=
 array([[0., 0.],
        [0., 0.]], dtype=float32)>)

## tf.math,log  tf.exp

In [5]:
a

<tf.Tensor: id=2, shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [6]:
tf.math.log(a)

<tf.Tensor: id=12, shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [7]:
tf.exp(a)

<tf.Tensor: id=13, shape=(2, 2), dtype=float32, numpy=
array([[2.7182817, 2.7182817],
       [2.7182817, 2.7182817]], dtype=float32)>

## log2, log10?

In [8]:
tf.math.log(8.) / tf.math.log(2.)

<tf.Tensor: id=18, shape=(), dtype=float32, numpy=3.0>

In [9]:
tf.math.log(100.) / tf.math.log(10.)

<tf.Tensor: id=23, shape=(), dtype=float32, numpy=2.0>

## pow, sqrt

In [10]:
b

<tf.Tensor: id=5, shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [2., 2.]], dtype=float32)>

In [11]:
tf.pow(b, 3)

<tf.Tensor: id=25, shape=(2, 2), dtype=float32, numpy=
array([[8., 8.],
       [8., 8.]], dtype=float32)>

In [12]:
b ** 3

<tf.Tensor: id=27, shape=(2, 2), dtype=float32, numpy=
array([[8., 8.],
       [8., 8.]], dtype=float32)>

In [13]:
tf.sqrt(b)

<tf.Tensor: id=28, shape=(2, 2), dtype=float32, numpy=
array([[1.4142135, 1.4142135],
       [1.4142135, 1.4142135]], dtype=float32)>

## @ matmul

In [14]:
a, b

(<tf.Tensor: id=2, shape=(2, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.]], dtype=float32)>,
 <tf.Tensor: id=5, shape=(2, 2), dtype=float32, numpy=
 array([[2., 2.],
        [2., 2.]], dtype=float32)>)

In [15]:
a @ b

<tf.Tensor: id=29, shape=(2, 2), dtype=float32, numpy=
array([[4., 4.],
       [4., 4.]], dtype=float32)>

In [16]:
tf.matmul(a, b)

<tf.Tensor: id=30, shape=(2, 2), dtype=float32, numpy=
array([[4., 4.],
       [4., 4.]], dtype=float32)>

In [17]:
a = tf.ones([4, 2, 3])
b = tf.fill([4, 3, 5], 2.)

In [18]:
a @ b

<tf.Tensor: id=37, shape=(4, 2, 5), dtype=float32, numpy=
array([[[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]]], dtype=float32)>

In [19]:
tf.matmul(a, b)

<tf.Tensor: id=38, shape=(4, 2, 5), dtype=float32, numpy=
array([[[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]]], dtype=float32)>

## With broadcasting

In [20]:
b = tf.fill([3, 5], 2.)
b.shape

TensorShape([3, 5])

In [21]:
bb = tf.broadcast_to(b, [4, 3, 5])

In [22]:
a @ bb

<tf.Tensor: id=44, shape=(4, 2, 5), dtype=float32, numpy=
array([[[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]]], dtype=float32)>

## Y = X @ W + b

In [23]:
x = tf.ones([4, 2])
W = tf.ones([2, 1])
b = tf.constant(0.1)

x @ W + b

<tf.Tensor: id=53, shape=(4, 1), dtype=float32, numpy=
array([[2.1],
       [2.1],
       [2.1],
       [2.1]], dtype=float32)>

## out = relu(X @ W + b)

In [24]:
x @ W + b

<tf.Tensor: id=55, shape=(4, 1), dtype=float32, numpy=
array([[2.1],
       [2.1],
       [2.1],
       [2.1]], dtype=float32)>

In [26]:
out = x @ W + b

out = tf.nn.relu(out)
out

<tf.Tensor: id=61, shape=(4, 1), dtype=float32, numpy=
array([[2.1],
       [2.1],
       [2.1],
       [2.1]], dtype=float32)>

# 向前传播实战

## relu[X @ W1 + b1]

In [28]:
w1, b1 = tf.Variable(tf.random.truncated_normal([784, 512], stddev=0.1)), tf.Variable(tf.zeros([512]))

for step, (x, y) in enumerate(train_db):
    # [b, 28, 28] => [b, 784]
    x = tf.reshape(x, (-1, 784))
    with tf.GradientTape() as tape:
        # layer1
        h1 = x @ w1 + b1
        h1 = tf.nn.relu(h1)

NameError: name 'train_db' is not defined

# 合并与分割

## concat

In [29]:
a = tf.ones([4, 35, 8])
b = tf.ones([2, 35, 8])

c = tf.concat([a, b], axis=0)
c.shape

TensorShape([6, 35, 8])

In [31]:
a = tf.ones([4, 35, 8])
b = tf.ones([4, 3, 8])

c = tf.concat([a, b], axis=1)
c.shape

TensorShape([4, 38, 8])

## stack

In [33]:
a = tf.ones([4, 35, 8])
b = tf.ones([4, 35, 8])

c = tf.concat([a, b], axis=-1)
c.shape

TensorShape([4, 35, 16])

In [35]:
d = tf.stack([a, b])
d.shape

TensorShape([2, 4, 35, 8])

In [39]:
e = tf.stack([a, b], axis=3)
e.shape

TensorShape([4, 35, 8, 2])

tf.concat 除合并维度之外的维度数量必须一致。
tf.stack 所有维度的数量必须都一致。

## unstack

In [43]:
a = tf.ones([4, 35, 8])
b = tf.ones([4, 35, 8])
c = tf.stack([a, b])
c.shape

TensorShape([2, 4, 35, 8])

In [44]:
aa, bb = tf.unstack(c, axis=0)
aa.shape, bb.shape

(TensorShape([4, 35, 8]), TensorShape([4, 35, 8]))

In [46]:
res = tf.unstack(c, axis=3)    # shuffle
res[0].shape, res[2].shape, res[7].shape

(TensorShape([2, 4, 35]), TensorShape([2, 4, 35]), TensorShape([2, 4, 35]))

## split

In [47]:
res = tf.unstack(c, axis=3)
len(res)

8

In [49]:
res = tf.split(c, axis=3, num_or_size_splits=2)
len(res)

(2, TensorShape([2, 4, 35, 4]))

In [50]:
res = tf.split(c, axis=3, num_or_size_splits=[3, 3, 2])
len(res), res[0].shape, res[1].shape, res[2].shape

(3,
 TensorShape([2, 4, 35, 3]),
 TensorShape([2, 4, 35, 3]),
 TensorShape([2, 4, 35, 2]))

# Tensor排序

## sort/argsort

In [51]:
a = tf.random.shuffle(tf.range(5))
a

<tf.Tensor: id=283, shape=(5,), dtype=int32, numpy=array([2, 0, 1, 3, 4])>

In [52]:
tf.sort(a, direction="DESCENDING")

<tf.Tensor: id=295, shape=(5,), dtype=int32, numpy=array([4, 3, 2, 1, 0])>

In [53]:
tf.argsort(a, direction="DESCENDING")

<tf.Tensor: id=309, shape=(5,), dtype=int32, numpy=array([4, 3, 0, 2, 1])>

In [54]:
idx = tf.argsort(a, direction="DESCENDING")
a_sorted = tf.gather(a, idx)
a_sorted

<tf.Tensor: id=324, shape=(5,), dtype=int32, numpy=array([4, 3, 2, 1, 0])>

### 行维度上排序

In [55]:
a = tf.random.uniform([3, 3], maxval=10, dtype=tf.int32)
a

<tf.Tensor: id=332, shape=(3, 3), dtype=int32, numpy=
array([[6, 1, 4],
       [1, 8, 5],
       [4, 5, 7]])>

In [56]:
tf.sort(a, direction="DESCENDING")

<tf.Tensor: id=344, shape=(3, 3), dtype=int32, numpy=
array([[6, 4, 1],
       [8, 5, 1],
       [7, 5, 4]])>

In [57]:
tf.argsort(a, direction="DESCENDING")

<tf.Tensor: id=358, shape=(3, 3), dtype=int32, numpy=
array([[0, 2, 1],
       [1, 2, 0],
       [2, 1, 0]])>

### 列维度上排序

In [59]:
a = tf.random.uniform([3, 3], maxval=10, dtype=tf.int32)
a

<tf.Tensor: id=381, shape=(3, 3), dtype=int32, numpy=
array([[7, 1, 4],
       [6, 7, 6],
       [9, 6, 5]])>

In [60]:
tf.sort(a, direction="DESCENDING", axis=0)

<tf.Tensor: id=397, shape=(3, 3), dtype=int32, numpy=
array([[9, 7, 6],
       [7, 6, 5],
       [6, 1, 4]])>

In [61]:
tf.argsort(a, direction="DESCENDING", axis=0)

<tf.Tensor: id=413, shape=(3, 3), dtype=int32, numpy=
array([[2, 1, 1],
       [0, 2, 2],
       [1, 0, 0]])>

## Top_k

In [62]:
a = tf.random.uniform([3, 3], maxval=10, dtype=tf.int32)
a

<tf.Tensor: id=421, shape=(3, 3), dtype=int32, numpy=
array([[8, 5, 9],
       [4, 7, 7],
       [2, 2, 8]])>

In [63]:
res = tf.math.top_k(a, k=1, sorted=True)

In [64]:
res.values

<tf.Tensor: id=427, shape=(3, 1), dtype=int32, numpy=
array([[9],
       [7],
       [8]])>

In [65]:
res.indices

<tf.Tensor: id=428, shape=(3, 1), dtype=int32, numpy=
array([[2],
       [1],
       [2]])>

## Top_k accuracy

In [67]:
prob = tf.constant([[0.1, 0.2, 0.7], [0.2, 0.7, 0.1]])
target = tf.constant([2, 0])

k_b = tf.math.top_k(prob, k=2).indices
k_b

<tf.Tensor: id=456, shape=(2, 2), dtype=int32, numpy=
array([[2, 1],
       [1, 0]])>

In [68]:
target = tf.broadcast_to(target, [2, 2])
target

<tf.Tensor: id=462, shape=(2, 2), dtype=int32, numpy=
array([[2, 0],
       [2, 0]])>

In [69]:
correct = tf.equal(target, k_b)
correct

<tf.Tensor: id=467, shape=(2, 2), dtype=bool, numpy=
array([[ True, False],
       [False,  True]])>

In [70]:
bool2int = tf.cast(correct, dtype=tf.int32)
bool2int

<tf.Tensor: id=472, shape=(2, 2), dtype=int32, numpy=
array([[1, 0],
       [0, 1]])>

In [71]:
num_of_pre_correct = tf.reduce_sum(bool2int)
num_of_pre_correct

<tf.Tensor: id=478, shape=(), dtype=int32, numpy=2>

In [73]:
top_k_accuracy = num_of_pre_correct / target.shape[0]
top_k_accuracy

<tf.Tensor: id=494, shape=(), dtype=float64, numpy=1.0>

# 数据加载

## 导入库

In [1]:
import tensorflow as tf
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import sklearn
import pandas as pd
import os
import sys
import time
from tensorflow import keras

print(sys.version_info)
for module in mpl, np, pd, sklearn, tf, keras:
    print(module.__name__ + "的版本为：" + module.__version__)

sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
matplotlib的版本为：3.0.3
numpy的版本为：1.16.2
pandas的版本为：0.25.3
sklearn的版本为：0.20.3
tensorflow的版本为：2.0.0
tensorflow_core.keras的版本为：2.2.4-tf


## 采用tf.keras.datasets加载boston housing 数据集，并观测该数据的shape

In [2]:
(x, y), (x_test, y_test) = keras.datasets.boston_housing.load_data()

print(x.shape, y.shape)
print(x_test.shape, y_test.shape)

(404, 13) (404,)
(102, 13) (102,)


## 采用tf.keras.datasets加载mnist/fashion mnist ,并展示该给前50数据

In [3]:
mnist = keras.datasets.mnist.load_data()

In [4]:
mnist[:50]

((array([[[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         ...,
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0

In [8]:
fashion_mnist = keras.datasets.fashion_mnist.load_data()

In [9]:
fashion_mnist[:50]

((array([[[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         ...,
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0

## 采用tf.keras.datasets加载cifar10/100 ,并展示该给前100数据

In [3]:
cifar10 = tf.keras.datasets.cifar10.load_data()

In [4]:
cifar10[:2]

((array([[[[ 59,  62,  63],
           [ 43,  46,  45],
           [ 50,  48,  43],
           ...,
           [158, 132, 108],
           [152, 125, 102],
           [148, 124, 103]],
  
          [[ 16,  20,  20],
           [  0,   0,   0],
           [ 18,   8,   0],
           ...,
           [123,  88,  55],
           [119,  83,  50],
           [122,  87,  57]],
  
          [[ 25,  24,  21],
           [ 16,   7,   0],
           [ 49,  27,   8],
           ...,
           [118,  84,  50],
           [120,  84,  50],
           [109,  73,  42]],
  
          ...,
  
          [[208, 170,  96],
           [201, 153,  34],
           [198, 161,  26],
           ...,
           [160, 133,  70],
           [ 56,  31,   7],
           [ 53,  34,  20]],
  
          [[180, 139,  96],
           [173, 123,  42],
           [186, 144,  30],
           ...,
           [184, 148,  94],
           [ 97,  62,  34],
           [ 83,  53,  34]],
  
          [[177, 144, 116],
           [16

In [2]:
cifar100 = tf.keras.datasets.cifar100.load_data()

169009152/169001437 [==============================] - 2307s 14us/step


In [3]:
cifar100[:2]

((array([[[[255, 255, 255],
           [255, 255, 255],
           [255, 255, 255],
           ...,
           [195, 205, 193],
           [212, 224, 204],
           [182, 194, 167]],
  
          [[255, 255, 255],
           [254, 254, 254],
           [254, 254, 254],
           ...,
           [170, 176, 150],
           [161, 168, 130],
           [146, 154, 113]],
  
          [[255, 255, 255],
           [254, 254, 254],
           [255, 255, 255],
           ...,
           [189, 199, 169],
           [166, 178, 130],
           [121, 133,  87]],
  
          ...,
  
          [[148, 185,  79],
           [142, 182,  57],
           [140, 179,  60],
           ...,
           [ 30,  17,   1],
           [ 65,  62,  15],
           [ 76,  77,  20]],
  
          [[122, 157,  66],
           [120, 155,  58],
           [126, 160,  71],
           ...,
           [ 22,  16,   3],
           [ 97, 112,  56],
           [141, 161,  87]],
  
          [[ 87, 122,  41],
           [ 8

## 采用tf.keras.datasets加载IMDB

In [4]:
imdb = tf.keras.datasets.imdb.load_data()

In [5]:
imdb[:2]

((array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
         list([1, 19

## 对minst数据集进行实战测试